#:kivy 2.0




# 
<ColorScheme@Widget>:
    back_color: [ 1, 1, 1, 1]
    text_color: [ 0, 0, 0, 1]
    bord_color: [ 0, 0,.5, 1]

    canvas.before:
        Color:
            rgba: self.back_color
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: self.bord_color
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height





<PushButton@Button+ColorScheme>:
    color: self.text_color

<TextLabel@Label+ColorScheme>:
    color: self.text_color





MyManager:
    id: manager

    back_color: [ 1, 1, 1, 1]

    ImageScreen:

    ButtonScreen: